PMM-7: POC

diff --git a/.github/workflows/runner-package-test.yml b/.github/workflows/runner-package-test.yml
--- a/.github/workflows/runner-package-test.yml
+++ b/.github/workflows/runner-package-test.yml
@@ -260,72 +260,41 @@ jobs:
         run: |
           timeout 240 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://127.0.0.1/v1/readyz)" != "200" ]]; do sleep 2; done' || false
 
-      - name: "Create vagrantfile"
-        working-directory: ./
-        run: |
-          pwd
-          # mkdir -p ~/test-vm/
-          # cat > ~/test-vm/Vagrantfile <<EOF
-          cat > Vagrantfile <<EOF
-          Vagrant.require_version ">= 1.7.0"
-          Vagrant.configure(2) do |config|
-            config.vm.box = "${{ env.VM_BOX }}"
-            ${{ contains(env.VM_BOX, 'debian10') && 'config.vbguest.auto_update = true' }}
-            config.ssh.insert_key = false
-            config.vm.define :CLIENT_TEST do |t|
-            end
-
-            config.vm.synced_folder "${{ github.workspace }}/", "/pmm/package-testing/"
-            config.vm.provision "shell", privileged: true, inline: <<-SHELL
-              ## Set environment variables...
-              export PMM_SERVER_IP=10.0.2.2:443
-              export METRICS_MODE=${{ env.METRICS_MODE }}
-              export PMM_VERSION="${{ env.EXPECTED_VERSION }}"
-              echo $PMM_VERSION
-              if [[ "${{ env.TARBALL_LINK }}" != "null" ]]; then
-                export TARBALL_LINK="${{ env.TARBALL_LINK }}"
-              fi
-              export install_repo=${{ env.REPO }}
-              export install_package=${{ env.INSTALL_PACKAGE }}
-              
-              if [[ "${{ env.VM_BOX }}" =~ "oracle" ]]; then
-                sudo dnf install -y epel-release
-                sudo dnf -y update
-                sudo dnf install -y ansible-core git wget dpkg
-              fi
-              if [[ "${{ env.VM_BOX }}" =~ "al2023" ]]; then
-                sudo dnf -y update
-                sudo dnf install -y ansible git wget tar
-              fi
-              if [[ "${{ env.VM_BOX }}" =~ "debian" ]]; then
-                sudo apt-get install -y dirmngr gnupg2
-                echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list > /dev/null
-                sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
-                sudo apt update -y
-                sudo apt-get install -y ansible git wget
-              fi
-              if [[ "${{ env.VM_BOX }}" =~ "ubuntu" ]]; then
-                sudo apt update -y
-                sudo apt install -y software-properties-common
-                sudo apt-add-repository --yes --update ppa:ansible/ansible
-                sudo apt-get install -y ansible git wget
-              fi
-              if [[ "${{ env.VM_BOX }}" =~ "oracle" ]]; then
-                sudo dnf -y install dnf-plugins-core
-                sudo dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
-                sudo dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
-                sudo systemctl enable --now docker
-              fi
-              cd /pmm/package-testing/playbooks
-              ansible-playbook -vv --connection=local --inventory 127.0.0.1, --limit 127.0.0.1 ${{ env.PLAYBOOK }}.yml
-              SHELL
-          end
-
-          EOF
-
       - name: "Run (${{ contains(env.TARBALL, 'PR-') && 'feature build' || inputs.repository }})${{ inputs.playbook }} test on ${{ inputs.os }}"
         working-directory: ./
-        run: vagrant up
+        run: |
+          cat > test_runner.sh <<'EOF'
+            #!/bin/bash
+            if [ -f /etc/os-release ]; then
+              . /etc/os-release
+            else
+              echo "Cannot detect distribution (no /etc/os-release)"
+              exit 1
+            fi
+
+            distro_id="${ID,,}"
+            distro_like="${ID_LIKE,,}"
+            echo "Detected distribution: ID=${distro_id}  ID_LIKE=${distro_like}"
+            # Helper predicates
+            is_debian_like() { [[ "$distro_id" == "debian" || "$distro_id" == "ubuntu" || "$distro_like" == *"debian"* ]]; }
+            is_rhel_like()   { [[ "$distro_id" =~ ^(rhel|centos|rocky|almalinux|fedora|ol|oracle)$ || "$distro_like" == *"rhel"* || "$distro_like" == *"fedora"* ]]; }
+
+            if is_debian_like; then
+	          apt-get update
+              apt-get install -y apt-transport-https ca-certificates ansible git wget
+            elif is_rhel_like; then
+              dnf update -y > /dev/null
+              dnf install -y git wget ansible-core
+            fi
+
+            ansible-playbook -vvv --connection=local --inventory 127.0.0.1, --limit 127.0.0.1 playbooks/${{ env.PLAYBOOK }}.yml
+          EOF
+          
+          chmod +x test_runner.sh
+          docker run --rm \
+            -v $(pwd)/test.sh:/test.sh \
+            --entrypoint /test.sh \
+            rockylinux:9
 
       - uses: actions/upload-artifact@v4
         if: ${{ failure() }}
